### ISSUE TITLE
Error in cardCryptogram

### ISSUE THREAD

**Issue by gazaret** [cloudpayments/CloudPayments_AndroidSDKDemo#10]
При вызове метода получаю ошибку:
![default](https://user-images.githubusercontent.com/7079482/40042680-44cb0d86-5833-11e8-8b05-c854ac3a1cc5.png)

Public ID передаю валидный (API его принимает)

**Comment by ign4** [comment]
Добрый день! Вы используете старое СДК или новое? Дайте ссылку.

2018-05-15 12:31 GMT+05:00 Nikolay Polukhin <notifications@github.com>:

**Comment by ign4** [comment]
https://github.com/cloudpayments/CloudPayments_AndroidCheckout - здесь новая версия, попробуйте ее

**Comment by gazaret** [comment]
@ign4 на новой версии заработало, правда при передачи всех данных карты
```
Card card = CardFactory.create(String number, String expDate, String cvv);
```
если передавать только номер карты, то так же будет ошибка

**Comment by ign4** [comment]
Хорошо, учтем замечание, спасибо!
