### ISSUE TITLE
Отправка произвольных данных в data json при оплате

### ISSUE THREAD

**Issue by tridetch** [cloudpayments/CloudPayments_AndroidSDKDemo#8]
Позволяет ли skd отправлять произвольные данные в data json по аналогии с веб версией платежного виджета?

**Comment by ign4** [comment]
Все что позволяет SDK описано в документации, Вы можете либо использовать готовую форму для ввода данных карты либо создать свою, оба этих способа реализовано в demo примере.

**Comment by ign4** [comment]
В настоящий момент нет такой возможности, добавим такую возможность в самое ближайшее время.

**Comment by ign4** [comment]
В SDK добавлена возможность отправлять произвольные данные, пример отправки реализован в тестовом приложении, Вы можете использовать эту возможность обновив файл 
 SDK в своем проекте.
