### ISSUE TITLE
Не проходит оплата картой Тинькофф (Cross Site Scripting attack...)

### ISSUE THREAD

**Issue by tridetch** [cloudpayments/CloudPayments_AndroidSDKDemo#9]
При попытке провести оплату картой банка Тинькофф появляется сообщение: "Cross Site Scripting attack was detected. The transaction was stopped.". При оплате через веб версию виджета все проходит нормально.
![cross site scripting](https://user-images.githubusercontent.com/16163869/31662698-29251e86-b348-11e7-9228-b2733a038df7.jpg)

**Comment by ign4** [comment]
Ошибка исправлена, обновите файл нашей библиотеки в Вашем проекте, так же обращаем Ваше внимание, добавилась возможность проведения одностадийного платежа во встроенную форму и теперь при запуске встроенной формы необходимо указать тип платежа:
intent.putExtra(PaymentWidget.EXTRA_TYPE, PaymentWidget.TYPE_AUTH); // Тип платежа: TYPE_CHARGE (одностадийный) или TYPE_AUTH (двухстадийный)
